[[tie]]
name = ".gitignore -> trivy.yaml"
source = ".gitignore"
target = "trivy.yaml"
transform = "transform:trivy_yaml"

[[tie]]
name = "mcp.json"
source = ".ties/mcp-tie.json"
targets = [".mcp.json", ".cursor/mcp.json"]
transform = "ties:embed_environ"

[[tie]]
name = "Claude Instructions"
source = ".ties/instructions-tie.md"
target = "CLAUDE.md"

[[tie]]
name = "VSCode Instructions"
sources = [".ties/vscode_header.txt", ".ties/instructions-tie.md"]
target = ".github/copilot-instructions.md"

[[tie]]
name = "Cursor Instructions"
sources = [".ties/cursor_header.txt", ".ties/instructions-tie.md"]
target = ".cursor/rules/instructions.mdc"
