env_list = [ "py313", "coverage" ]

[env_run_base]
runner = "uv-venv-lock-runner"
description = "Run test under {base_python}"
skip_install = true
commands = [ [ "pytest", { replace = "posargs", default = [ "tests" ], extend = true } ] ]

[env.coverage]
base_python = [ "py313" ]
commands = [
  [
    "pytest",
    "tests",
    "--cov",
    "--cov-report=term-missing",
    "--cov-report=lcov:lcov.info",
    "--cov=src/{{cookiecutter.project_slug}}",
    "--cov-fail-under=95",
  ],
]
