---
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Cookiecutter PyProject 2025 CI build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.13']
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Install the project
        run: uv sync --locked --all-extras
      # - name: Lint with ruff
      #   run: |
      #     # Stop the build if the formatting is bad
      #     ruff format . --check
      #     # stop the build if there is ugly python
      #     ruff check .
      - name: Test with pytest
        run: |
          pytest tests/
      # - name: Check types with mypy
      #   run: |-
      #     ty check .